// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_devils_due = "CgkI-MWprNwaEAIQCQ"; // <GPGSID>
        public const string achievement_15k = "CgkI-MWprNwaEAIQBw"; // <GPGSID>
        public const string achievement_8_in_one_go = "CgkI-MWprNwaEAIQDQ"; // <GPGSID>
        public const string achievement_20k = "CgkI-MWprNwaEAIQCA"; // <GPGSID>
        public const string leaderboard_time_attack = "CgkI-MWprNwaEAIQAw"; // <GPGSID>
        public const string achievement_6_in_one_go = "CgkI-MWprNwaEAIQCw"; // <GPGSID>
        public const string achievement_7_in_one_go = "CgkI-MWprNwaEAIQDA"; // <GPGSID>
        public const string achievement_10k = "CgkI-MWprNwaEAIQBg"; // <GPGSID>
        public const string leaderboard_limited_turns = "CgkI-MWprNwaEAIQAg"; // <GPGSID>
        public const string achievement_all_the_power_ups = "CgkI-MWprNwaEAIQDw"; // <GPGSID>
        public const string achievement_3k = "CgkI-MWprNwaEAIQBA"; // <GPGSID>
        public const string achievement_all_at_once = "CgkI-MWprNwaEAIQDg"; // <GPGSID>
        public const string achievement_5k = "CgkI-MWprNwaEAIQBQ"; // <GPGSID>
        public const string achievement_5_in_one_go = "CgkI-MWprNwaEAIQCg"; // <GPGSID>

}

